#!/bin/bash -x
set -e

# config
host=root@brnbw.com
dir="/var/www/dldr.brnbw.com/public"
dest=build

# prepare
mkdir -p $dest
npm run build
cp index.html favicon.ico $dest

# transfer
ssh $host "mkdir -p $dir" && rsync -ruv --no-perms $dest/* $host:$dir

